version = 1

test_patterns = ["tests/**"]

exclude_patterns = ["examples/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  style_guide = "standard"